name: store
description: "跟着油管视频博主学习的项目"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Black.ttf
        - asset: assets/fonts/NotoSansSC-Bold.ttf
        - asset: assets/fonts/NotoSansSC-ExtraBold.ttf
        - asset: assets/fonts/NotoSansSC-ExtraLight.ttf
        - asset: assets/fonts/NotoSansSC-Light.ttf
        - asset: assets/fonts/NotoSansSC-Medium.ttf
        - asset: assets/fonts/NotoSansSC-Regular.ttf
        - asset: assets/fonts/NotoSansSC-SemiBold.ttf
        - asset: assets/fonts/NotoSansSC-Thin.ttf
